name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests jsonschema uvicorn

      - name: Run API contract tests
        run: |
          pytest -v tests/test_api_contract2.py

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: trungpham09nov/weather-api2:latest

# deploy:
#   runs-on: ubuntu-latest
#   needs: docker
#   steps:
#     - name: Deploy (example via SSH)
#       uses: appleboy/ssh-action@v1.0.3
#       with:
#         host: ${{ secrets.SERVER_HOST }}
#         username: ${{ secrets.SERVER_USER }}
#         key: ${{ secrets.SERVER_SSH_KEY }}
#         script: |
#           docker pull trungpham09nov/weather-api:latest
#           docker stop weather-api || true
#           docker rm weather-api || true
#           docker run -d -p 8000:8000 --name weather-api trungpham09nov/weather-api:latest
